/* ==============================================================================
   STEP 1: Customer Age Demographic & Revenue Segmentation
   
   Business Objective:
   - Calculate exact customer age dynamically from birthdate relative to the execution date.
   - Segment customers into structured age cohorts to evaluate demographic distribution 
     and aggregate revenue generated by each demographic bracket.
   
   SQL Techniques Used:
   - Common Table Expression (CTE): `customer_demographics` dynamically calculates exact age 
     accounting for birthday passing using `DATEDIFF` and `DATEADD` conditional logic.
   - Relational JOIN: Joins `gold.dim_customers` to `gold.fact_sales` on `customer_key`.
   - Derived Subquery: `customer_age_buckets` maps computed age into demographic categories via `CASE`.
   - Aggregation: Computes `COUNT(DISTINCT customer_key)` and `SUM(sales_amount)` grouped by cohort.
   ============================================================================== */
WITH customer_demographics AS (
    SELECT 
        c.customer_key,
        c.first_name,
        c.birthdate,
        DATEDIFF(year, c.birthdate, GETDATE()) - 
        CASE 
            WHEN DATEADD(year, DATEDIFF(year, c.birthdate, GETDATE()), c.birthdate) > GETDATE() 
            THEN 1 
            ELSE 0 
        END AS exact_age,
        s.sales_amount 
    FROM gold.dim_customers c
    JOIN gold.fact_sales s
        ON c.customer_key = s.customer_key
)
SELECT 
    Age_category,
    COUNT(DISTINCT customer_key) AS total_customers,
    SUM(sales_amount) AS Total_sales
FROM (
    SELECT 
        customer_key,
        sales_amount,
        CASE 
            WHEN exact_age < 20 THEN 'Teenagers (<20)'
            WHEN exact_age BETWEEN 20 AND 35 THEN 'Young Adults (20-35)'
            WHEN exact_age BETWEEN 36 AND 50 THEN 'Middle-Aged (36-50)'
            ELSE '50+' 
        END AS Age_category
    FROM customer_demographics
) AS customer_age_buckets
GROUP BY Age_category
ORDER BY Total_sales DESC;
/* ==============================================================================
   STEP 4: Product Cost Range Segmentation & Catalog Distribution
   
   Business Objective:
   - Categorize the product catalog into distinct cost tiers (Low, Mid, High, Premium) 
     to understand inventory structure and catalog distribution across manufacturing cost tiers.
   
   SQL Techniques Used:
   - CTE (`Product_Segments`): Segments product records using a conditional `CASE` expression based on unit cost.
   - Dimension Aggregation: Uses `COUNT(product_key)` to tally unique SKUs within each cost bucket.
   - Ordering: Sorts by product volume (`Total_products DESC`) to identify catalog density.
   ============================================================================== */

WITH Product_Segments AS
(Select 
product_key,
product_name,
cost,
CASE
   WHEN cost < 100 THEN 'Below 100'
   WHEN cost between 100 and 500 THEN '100-500'
    WHEN cost between 500 and 1000 THEN '500-1000'
	ELSE 'Above 1000' END AS Cost_range
from gold.dim_products)

SELECT cost_range,
COUNT(Product_key)AS Total_products
FROM Product_Segments
GROUP BY cost_range
ORDER BY Total_products DESC
/* ==============================================================================
   STEP 5: Customer Behavioral Segmentation (Lifespan & Monetary Value)
   
   Business Objective:
   - Profile customer purchase behavior by calculating customer tenure (lifespan) 
     and aggregate lifetime expenditure.
   - Categorize customers into actionable behavioral cohorts (VIP, Regular, New) 
     to evaluate retention, lifetime value, and cohort revenue contribution.
   
   SQL Techniques Used:
   - Chained CTE 1 (`customer_aggregates`): Aggregates total spending, first/last order 
     dates, and tenure in months using `DATEDIFF(month, MIN(...), MAX(...))`.
   - Chained CTE 2 (`customer_behavior_segments`): References CTE 1 to assign cohorts 
     via conditional `CASE` logic based on spending threshold ($5,000) and tenure (12+ months).
   - Aggregation: Computes `COUNT(customer_key)` and `SUM(Total_spending)` per cohort.
   ============================================================================== */
WITH customer_lifetime_metrics AS
(SELECT
c.customer_key,
SUM(S.Sales_amount) AS Total_spending,
MIN(S.order_date) AS First_order,
MAX(S.order_date) AS Last_order,
DATEDIFF(MONTH,MIN(S.order_date),MAX(S.order_date)) AS Lifespan
FROM GOLD.fact_sales S
left join GOLD.dim_customers C
ON S.customer_key = C.customer_key
GROUP BY c.customer_key),

CTE_2_customer_behavior_segments AS 
(SELECT customer_key,
Total_spending,
CASE
      WHEN Lifespan >= 12 AND Total_spending > 5000 THEN 'VIP Customer'
      WHEN Lifespan >= 12 AND Total_spending <= 5000 THEN 'Regular Customer'
	  ELSE 'New Customer' END AS Customer_Segments
FROM customer_lifetime_metrics)

SELECT Customer_Segments,
COUNT(customer_key) AS Count_of_customer
from CTE_2_customer_behavior_segments
GROUP by Customer_Segments
order by COUNT(customer_key) DESC
 